author: "Lionheart Software"
author_url: "https://lionheartsw.com"
github_url: "https://github.com/lionheart/SuperLayout"
github_file_prefix: "https://github.com/lionheart/SuperLayout/tree/0.2.3"
xcodebuild_arguments: ["-project", "SuperLayout.xcodeproj", "-scheme", "SuperLayout"]
readme: "README.md"
copyright: "&copy; 2017 Lionheart Software LLC"
theme: fullwidth
head: "<style type='text/css'>body { font-family: -apple-system !important; }</style>"

